# see https://www.gitpod.io/docs/references/gitpod-yml#ports
tasks:
  - name: Setup & Build
    before: go mod download
    init: make build
    command: make run

ports:
  - port: 8080
    onOpen: open-preview
    name: Extension
    description: Extension HTTP interface
