
/*
# Welcome
*/
GET http://localhost:8080


/*
# Discovery
*/
GET http://localhost:8080/robot/discovery/target-description

GET http://localhost:8080/robot/discovery

GET http://localhost:8080/robot/discovery/discovered-targets

GET http://localhost:8080/robot/discovery/attribute-descriptions


/*
# Actions
*/
GET http://localhost:8080/robot/actions/log

/*
# Action Lifecycle

### Prepare
*/

POST http://localhost:8080/robot/actions/log/prepare
Content-Type: application/json

{
    "target": {
        "name": "R2-D2",
        "attributes": {}
    },
    "config": {
        "message": "Hello from %s!"
    }
}

/*
### Start
*/
POST http://localhost:8080/robot/actions/log/start
Content-Type: application/json

{
    "state": {
        "FormattedMessage": "Hello from R2-D2!"
    }
}

/*
### Status
*/
POST http://localhost:8080/robot/actions/log/status
Content-Type: application/json

{
    "state": {
        "FormattedMessage": "Hello from R2-D2!"
    }
}

/*
### Stop
*/
POST http://localhost:8080/robot/actions/log/stop
Content-Type: application/json

{
    "state": {
        "FormattedMessage": "Hello from R2-D2!"
    }
}

/*
# Events
*/
POST http://localhost:8080/events/all
Content-Type: application/json

{
  "id": "da059724-a8ae-4b4b-b4f0-ee01898232d2",
  "eventName": "experiment.execution.created",
  "eventTime": "2021-09-01T12:00:00Z",
  "tenant": {
    "key": "exmpl",
    "name": "Example Inc."
  },
  "principal": {
    "principalType": "user",
    "username": "tom.mason",
    "name": "Tom Mason",
    "email": "tom.mason@example.com"
  },
  "environment": {
    "id": "STG",
    "name": "Staging"
  },
  "team": {
    "key": "ADM",
    "name": "Administrators"
  },
  "experimentExecution": {
    "experimentKey": "ADM-4",
    "executionId": 34,
    "name": "Rollout restart does not impact service availability",
    "state": "COMPLETED",
    "preparedTime": "2022-11-08T16:42:32.303762Z",
    "startedTime": "2022-11-08T16:42:32.329718Z",
    "endedTime": "2022-11-08T16:42:42.636157Z"
  }
}

